### ISSUE TITLE
Remove 🍪

### ISSUE THREAD

**Issue by qdrn** [massalabs/thyra#15]
Produces the following error:
```
Error reading cookie
2022/06/28 11:31:39 http: panic serving [::1]:54455: http: named cookie not present
goroutine 421 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x150e4c0, 0xc000020b60})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
github.com/massalabs/thyra/pkg/onchain/website.handleSubsequentRequest({0x1741190, 0xc00063e1c0}, 0xc0000fee00)
	/Users/adrien/dev/thyra/pkg/onchain/website/website.go:52 +0x225
github.com/massalabs/thyra/pkg/onchain/website.HandlerFunc.func1({0x1741190, 0xc00063e1c0}, 0xc0000fee00)
	/Users/adrien/dev/thyra/pkg/onchain/website/website.go:112 +0x119
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1741190?, 0xc00063e1c0?}, 0x1a68bc0?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0xc00046e660?}, {0x1741190, 0xc00063e1c0}, 0xc0000fee00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000244d20, {0x1741538, 0xc0007b42a0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
```

**Comment by gregLibert** [comment]
Solve [here]([94b32e4](https://github.com/massalabs/thyra/commit/94b32e4e3b53c2c82676cc3cdcfd7bbcc194646f))
