### ISSUE TITLE
Fyne GUI not compatible with windows and mac VMs

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/thyra#592]
**The problem(s)**
I got an error when the gui bas supposed to open on macOS & windows on qemu
here is the error message on mac
```bash
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
[github.com/go-gl/glfw/v3.3/glfw.acceptError({0xc0005fbc08](https://github.com/go-gl/glfw/v3.3/glfw.acceptError(%7B0xc0005fbc08), 0x2, 0x101364ee0?})
 /Users/runner/go/pkg/mod/[github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/error.go:178](https://github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/error.go:178) +0x1c5
[github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0xc0008b4000](https://github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0xc0008b4000)?, 0xc0000062e8?, {0x1009012c8?, 0x100528ee0?}, 0x0, 0x0)
 /Users/runner/go/pkg/mod/[github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:350](https://github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:350) +0x172
[fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1()](https://fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1())
 /Users/runner/go/pkg/mod/[fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window_desktop.go:666](https://fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window_desktop.go:666) +0x12b
[fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003ca770)](https://fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003ca770))
 /Users/runner/go/pkg/mod/[fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:129](https://fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:129) +0x1cc
[fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x10076d7e9?)](https://fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x10076d7e9?))
 /Users/runner/go/pkg/mod/[fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver.go:164](https://fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver.go:164) +0x33
[fyne.io/fyne/v2/app.(*fyneApp).Run(0x0?)](https://fyne.io/fyne/v2/app.(*fyneApp).Run(0x0?))
 /Users/runner/go/pkg/mod/[fyne.io/fyne/v2@v2.2.3/app/app.go:68](https://fyne.io/fyne/v2@v2.2.3/app/app.go:68) +0x37
main.main()
 /Users/runner/work/thyra/thyra/cmd/thyra-server/main.go:71 +0x1fb
```

**To Reproduce**

get the ubuntu vm [here](https://github.com/massalabs/thyra-test-e2e/blob/main/INSTALLATION.md#virtual-machines)
& go on thyra

**Expected behavior(s)**
GUI to open and ask for the password or other fields
**Screenshots**
I pasted the macOs log and here is the error I got on windows 
![image](https://user-images.githubusercontent.com/83134981/230090520-602ff9d2-2383-40b3-9267-481aafa5de30.png)

**Thyra version**
v0.1.12

**Desktop (please complete the following information):**
macOS catalina & windows11 on qemu
 
 **Any other useful info**
some similar issues : 
 - https://github.com/go-flutter-desktop/go-flutter/issues/186
 - https://github.com/fyne-io/fyne/issues/2373

**Comment by SlnPons** [comment]
We are moving to Wails. And will test again.
